# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aa39a6c4944dcec30327fa686c35d6310ad70aaac1e0f928d6954545c32ad2e5ed8a88399a401cabef4389369a44ed00309c1795edce63432deb885c61b9eb5

test:
  secret_key_base: fe6a2e877607555bf82d540b9e099ac1807c2fd61c9dc58cea9489ff608dc3a67ea0fdb10a1dcc666a8c62454665afc263f60698518206958e934aeca437b3f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
